### ISSUE TITLE
README.md - last step

### ISSUE THREAD

**Issue by crazedVic** [adrianhunter/snowpack-svelte-routify-template#8]
Pretty new to this but when i ran thru your steps, snowpack dev just ended up giving me this error:
```
Build Error: C:\Users\User\routify-snowpack\node_modules\@snowpack\plugin-svelte\plugin.js
TypeError: Cannot read property 'map' of null

Source
C:\Users\User\routify-snowpack\src\App.svelte
TypeError: Cannot read property 'map' of null
    at C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\build\build-pipeline.js:70:37
    at Array.forEach (<anonymous>)
    at runPipelineLoadStep (C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\build\build-pipeline.js:63:37)
    at async Object.buildFile (C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\build\build-pipeline.js:219:24)
    at async C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\commands\dev.js:548:41
    at async buildFile (C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\commands\dev.js:561:24)
    at async loadUrl (C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\commands\dev.js:886:30)
    at async Server.handleRequest (C:\Users\User\AppData\Roaming\npm\node_modules\snowpack\lib\commands\dev.js:968:28)
```

I eventually figured out that running *npm start* however worked great.

Thanks for this template.  huge help.

**Comment by adrianhunter** [comment]
Not sure whats the issue here. I recommend to wait for the new svelt@next of doing things. Create a new project with `npm init svelt@next` and choose the static adapter. Watch the latest video from rich https://youtu.be/qSfdtmcZ4d0
